source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GSPlayer_Example', :exclusive => true do
  pod 'GSPlayer', :path => '../'
end

target 'GSPlayer_Tests', :exclusive => true do
  pod 'GSPlayer', :path => '../'

  
end
